name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ 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 }}
        issue-message: "Thanks for raising an issue. I will be back within a short time to check the issue' first issue"
        pr-message: "Congratulations you have made your first pull request. Wait for the owner to review and merge it' first pull request"
